version: '3.7'

services:
  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: unless-stopped
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "8404:8404"
